services:
  tracker:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - ENV=demo
      - DB_URL=jdbc:postgresql://db/$DB_USER

  db:
    restart: unless-stopped
    image: postgres:17-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"

volumes:
  data:
